################################################
#                 WARNING!                     #
# This file has been auto-generated by xdress. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################
"""
"""
cimport cpp_distributions
from libcpp cimport bool as cpp_bool



def run_exchange(nsup, ncon, fraction, flag):
    """run_exchange(nsup, ncon, fraction, flag)
    no docstring for run_exchange, please file a bug report!"""
    cpp_distributions.run_exchange(<int> nsup, <int> ncon, <double> fraction, <bint> flag)






{'cpppxd_footer': '', 'pyx_header': '', 'pxd_header': '', 'pxd_footer': '', 'cpppxd_header': '', 'pyx_footer': ''}
