################################################
#                 WARNING!                     #
# This file has been auto-generated by xdress. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################
"""
"""
cimport cpp_execute



def run_rxtr_req(n_supply=1, n_consume=1, con_node_avg=1, n_commod=1, con_commod_avg=1, excl_prob=0.0, connect_prob=1.0):
    """run_rxtr_req(n_supply=1, n_consume=1, con_node_avg=1, n_commod=1, con_commod_avg=1, excl_prob=0.0, connect_prob=1.0)
    no docstring for run_rxtr_req, please file a bug report!"""
    cpp_execute.run_rxtr_req(<int> n_supply, <int> n_consume, <int> con_node_avg, <int> n_commod, <int> con_commod_avg, <double> excl_prob, <double> connect_prob)






{'cpppxd_footer': '', 'pyx_header': '', 'pxd_header': '', 'pxd_footer': '', 'cpppxd_header': '', 'pyx_footer': ''}
