################################################
#                 WARNING!                     #
# This file has been auto-generated by xdress. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################
"""
"""
from libc.stdlib cimport free





cdef class RequestRC:
    """no docstring for {'tarbase': 'run_control', 'tarname': 'RequestRC', 'language': 'c++', 'srcname': 'RequestRC', 'sidecars': (), 'incfiles': ('cpp/run_control.h',), 'srcfiles': ('cpp/run_control.cc', 'cpp/run_control.h')}, please file a bug report!"""



    # constuctors
    def __cinit__(self, *args, **kwargs):
        self._inst = NULL
        self._free_inst = True

        # cached property defaults


    def __init__(self, ):
        """RequestRC(self, )
        """
        self._inst = new cpp_run_control.RequestRC()
    
    
    def __dealloc__(self):
        if self._free_inst:
            free(self._inst)

    # attributes

    # methods
    def i(self, ):
        """i(self, )
        no docstring for i, please file a bug report!"""
        cdef int rtnval
        rtnval = (<cpp_run_control.RequestRC *> self._inst).i()
        return int(rtnval)
    
    
    

    pass





cdef class SupplyRC:
    """no docstring for {'tarbase': 'run_control', 'tarname': 'SupplyRC', 'language': 'c++', 'srcname': 'SupplyRC', 'sidecars': (), 'incfiles': ('cpp/run_control.h',), 'srcfiles': ('cpp/run_control.cc', 'cpp/run_control.h')}, please file a bug report!"""



    # constuctors
    def __cinit__(self, *args, **kwargs):
        self._inst = NULL
        self._free_inst = True

        # cached property defaults


    def __init__(self, ):
        """SupplyRC(self, )
        """
        self._inst = new cpp_run_control.SupplyRC()
    
    
    def __dealloc__(self):
        if self._free_inst:
            free(self._inst)

    # attributes

    # methods
    def i(self, ):
        """i(self, )
        no docstring for i, please file a bug report!"""
        cdef int rtnval
        rtnval = (<cpp_run_control.SupplyRC *> self._inst).i()
        return int(rtnval)
    
    
    

    pass






{'cpppxd_footer': '', 'pyx_header': '', 'pxd_header': '', 'pxd_footer': '', 'cpppxd_header': '', 'pyx_footer': ''}
