"""Provides some useful tools for working with Cyclopts, including reporting
output.

:author: Matthew Gidden <matthew.gidden@gmail.com>
"""

import os
import tables as t
import uuid

def report(gparams, sparams, soln, sim_id = None, db_path = None):
    """Dumps parameter and solution information to an HDF5 database.
    
    Parameters
    ----------
    gparams : cyclopts.execute.GraphParams
        ExchangeGraph-defining parameters
    sparams : cyclopts.execute.SolverParams
        ExchangeSolver-defining parameters
    soln : cyclopts.execute.Solution
        The solved graph's solution.
    sim_id : int, optional
        The simulation id to use in the database. A UUID is generated by 
        default.
    db_path : os.path or similar, optional
        The database to dump information to. The default is cyclopts.h5 
        file placed in the current working directory.
    """
    db_path = os.path.join(os.getcwd(), 'cyclopts.h5') if db_path is None \
        else db_path
    sim_id = uuid.uuid4().int if sim_id is None else sim_id
    
    h5file = t.open_file(db_path, mode = "w", title = "Cyclopts Output")
    
